create procedure SP_RESERVACION

as
begin
    begin tran
        

end

EXEC SP_ALTASEDES 'CLN', 'CULIACAN', 'SINALOA', , ,0
EXEC SP_ALTASEDES 'MZT', 'MAZATLAN', 'SINALOA', , ,0
EXEC SP_ALTASEDES 'GDL', 'GUADALAJARA', 'JALISCO', , ,0
EXEC SP_ALTASEDES 'ENS', 'ENSENADA', 'BAJA CALIFORNIA', , ,0
EXEC SP_ALTASEDES 'XCO', 'XICO', 'VERACRUZ', , ,0

GO
EXEC SP_ALTACAMIONES 'GDE',0, 1500, 'DIESEL',1800, 'ASDFJ-23'  
EXEC SP_ALTACAMIONES 'GDE',0, 1500, 'DIESEL',8800, 'OEP-S239'  
EXEC SP_ALTACAMIONES 'CHI',0, 1500, 'DIESEL',1000, 'VHM-S239'  
  
EXEC SP_ALTACAMIONES 'MED',0, 1500, 'GASOLINA',1000, 'KJASK-0909'  
EXEC SP_ALTACAMIONES 'MED',0, 1500, 'DIESEL',1000, 'AKSW-8888'  
EXEC SP_ALTACAMIONES 'GDE',0, 1500, 'DIESEL',2000, 'VILM-516A'  
EXEC SP_ALTACAMIONES 'GDE',0, 1500, 'DIESEL',2000, 'VIFE-5892'  
EXEC SP_ALTACAMIONES 'GDE',0, 1500, 'DIESEL',6000, 'VIEX-6971'  
EXEC SP_ALTACAMIONES 'GDE',0, 1500, 'DIESEL',4500, 'KPEN-51WE'  
EXEC SP_ALTACAMIONES 'GDE',0, 1500, 'DIESEL',8000, '699S-D84S'  

execute asignaCamionSede 'NAV', 'MED0001'






----------------------------------------------------


USE MUDANZA
CREATE TABLE TRACE (
	ID_CAMION CHAR(7) NOT NULL,
	AUX_CAMION INT NOT NULL,
	ORIGEN VARCHAR(3) NOT NULL,
	DESTINO VARCHAR(3) NOT NULL,
	ESTATUS CHAR(1) NOT NULL,
	FECHA DATE NOT NULL,
    fechaDisponible date not null
	PRIMARY KEY(ID_CAMION,AUX_CAMION)
);
SELECT * FROM TRACE

INSERT INTO TRACE VALUES('GDE0002', 7, 'CLN', 'GVE', 'D', '03-09-2019');

--SELECT ID_CAMION FROM TRACE GROUP BY ID_CAMION

SELECT ID_CAMION  FROM TRACE WHERE SUBSTRING(ID_CAMION,0,4) = 'GDE'   GROUP BY ID_CAMION  

SELECT * FROM TRACE 


ALTER PROCEDURE SP_APARTADO
@P_TAM CHAR(3),
@P_ORIGEN VARCHAR(3),
@P_FECHA DATETIME
AS
BEGIN 
	BEGIN TRAN
		DECLARE
		@NUMERO INT,
		@MATRICULA CHAR(7)
		SET @MATRICULA = (
			SELECT  ID_CAMION FROM TRACE TR WITH (UPDLOCK)
			WHERE AUX_CAMION = (SELECT MAX(AUX_CAMION) FROM TRACE TAUX WHERE TR.ID_CAMION = TAUX.ID_CAMION) AND
			ESTATUS = 'D' AND
			DESTINO = @P_ORIGEN AND
			FECHA = @P_FECHA AND
			SUBSTRING(ID_CAMION,0,4) = @P_TAM
		);
		SET @NUMERO =( SELECT COUNT(@MATRICULA ) FROM TRACE WITH (UPDLOCK) WHERE ID_CAMION = @MATRICULA)
		IF(@MATRICULA != 'NULL')
			INSERT INTO TRACE VALUES ( @MATRICULA , @NUMERO + 1 , 'CLN', 'CLN', 'V', '03-09-2019' );
		
	COMMIT TRAN
END
SELECT 'MATRICULA' = @MATRICULA



EXEC SP_APARTADO 'GDE', 'GVE', '03-09-2019'
 

SELECT * FROM TRACE



SELECT * FROM TRACE T1
WHERE AUX_CAMION=(SELECT MAX(AUX_CAMION) FROM TRACE t2 WHERE t1.ID_CAMION=t2.ID_CAMION) AND ESTATUS = 'D' AND  SUBSTRING(ID_CAMION,0,4) = 'GDE';






